export const data = [
  {
    preview: "http://mobile.turancoin.net/media/preview_cards/logo_NlC7Me7.png",
    title: "Iphone xs max1",
    id: "2",
    discount_price: 7499,
    discount_amount: 35,
    price: 9000,
    calc_price: 7499,
    average_rate: 3.5,
    comments_amount: 125,
    main: false,
  },
  {
    preview: "http://mobile.turancoin.net/media/preview_cards/logo_NlC7Me7.png",
    title: "Iphone xs max1",
    id: "2",
    discount_price: 7499,
    discount_amount: 35,
    price: 9000,
    calc_price: 7499,
    average_rate: 3.5,
    comments_amount: 125,
    main: false,
  },
  {
    preview: "http://mobile.turancoin.net/media/preview_cards/logo_NlC7Me7.png",
    title: "Iphone xs max1",
    id: "2",
    discount_price: 7499,
    discount_amount: 35,
    price: 9000,
    calc_price: 7499,
    average_rate: 3.5,
    comments_amount: 125,
    main: false,
  },
  {
    preview: "http://mobile.turancoin.net/media/preview_cards/logo_NlC7Me7.png",
    title: "Iphone xs max1",
    id: "2",
    discount_price: 7499,
    discount_amount: 35,
    price: 9000,
    calc_price: 7499,
    average_rate: 3.5,
    comments_amount: 125,
    main: false,
  },
  {
    preview: "http://mobile.turancoin.net/media/preview_cards/logo_NlC7Me7.png",
    title: "Iphone xs max1",
    id: "2",
    discount_price: 7499,
    discount_amount: 35,
    price: 9000,
    calc_price: 7499,
    average_rate: 3.5,
    comments_amount: 125,
    main: false,
  },
  {
    preview: "http://mobile.turancoin.net/media/preview_cards/logo_NlC7Me7.png",
    title: "Iphone xs max1",
    id: "2",
    discount_price: 7499,
    discount_amount: 35,
    price: 9000,
    calc_price: 7499,
    average_rate: 3.5,
    comments_amount: 125,
    main: false,
  },
  {
    preview: "http://mobile.turancoin.net/media/preview_cards/logo_NlC7Me7.png",
    title: "Iphone xs max2",
    id: "2",
    discount_price: 7499,
    discount_amount: 35,
    price: 9000,
    calc_price: 7499,
    average_rate: 3.5,
    comments_amount: 125,
    main: false,
  },
  
];
