export const data = [
  {
    image: require("../../images/shop/productItem.png"),
    name: "Iphone xs max1",
    id: "2",
    price: 7499,
    discount_amount: 35,
    full_price: 9000,
    rate: 3.5,
    reply_amount: 125,
    main: false,
  },
  {
    image: require("../../images/shop/productItem.png"),
    name: "Iphone xs max",
    id: "1",
    price: 7499,
    discount_amount: 35,
    full_price: 9000,
    rate: 3.5,
    reply_amount: 125,
    main: false,
  },
  {
    image: require("../../images/shop/productItem.png"),
    name: "Iphone xs max",
    id: "1",
    price: 7499,
    discount_amount: 35,
    full_price: 9000,
    rate: 3.5,
    reply_amount: 125,
    main: false,
  },
  {
    image: require("../../images/shop/productItem.png"),
    name: "Iphone xs max",
    id: "1",
    price: 7499,
    discount_amount: 35,
    full_price: 9000,
    rate: 3.5,
    reply_amount: 125,
    main: false,
  },
  {
    image: require("../../images/shop/productItem.png"),
    name: "Iphone xs max",
    id: "1",
    price: 7499,
    discount_amount: 35,
    full_price: 9000,
    rate: 3.5,
    reply_amount: 125,
    main: false,
  },
];
