export const SET_TOKEN = "SET_TOKEN";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PAYMENT_METHODS = "GET_PAYMENT_METHODS";
export const GET_DELIERY_METHODS = "GET_DELIERY_METHODS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_ORDER = "GET_ORDER";
export const GET_SHOP = "GET_SHOP";

export const CREATE_CARD = "CREATE_CARD";
export const CREATE_CARD_COMMENT = "CREATE_CARD_COMMENT";
export const CREATE_CARD_RATE = "CREATE_CARD_RATE";
export const CREATE_SHOP_RATE = "CREATE_SHOP_RATE";
export const CREATE_SHOP_COMMENT = "CREATE_SHOP_COMMENT";
export const CREATE_SHOP = "CREATE_SHOP";
export const CREATE_COUPON = "CREATE_COUPON";
export const CREATE_ADDRESS = "CREATE_ADDRESS";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_ITEM = "CREATE_ORDER_ITEM";

export const DELETE_SHOP = "DELETE_SHOP";

export const PARTIAL_UPDATE_SHOP = "PARTIAL_UPDATE_SHOP";
